const EP = {
  AUTH: {
    LOGIN:           '/auth/login',
    REGISTER:        '/auth/register',
    LOGOUT:          '/auth/logout',
    REFRESH:         '/auth/refresh',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD:  '/auth/reset-password',
    VERIFY_EMAIL:    '/auth/verify-email',
    ME:              '/auth/me',
  },
  EVENTS: {
    LIST:     '/events',
    SEARCH:   '/events/search',
    FEATURED: '/events/featured',
    TRENDING: '/events/trending',
    GET:      (id) => `/events/${id}`,
    CREATE:   '/events',
    UPDATE:   (id) => `/events/${id}`,
    DELETE:   (id) => `/events/${id}`,
    IMAGE:    (id) => `/events/${id}/image`,
  },
  REGISTRATIONS: {
    REGISTER:   (eventId) => `/registrations/events/${eventId}`,
    CANCEL:     (eventId) => `/registrations/events/${eventId}`,
    MY:         '/registrations/my',
    EVENT_LIST: (eventId) => `/registrations/events/${eventId}`,
    CHECK:      (eventId) => `/registrations/events/${eventId}/check`,
  },
  TICKETS: {
    MY:       '/tickets/my',
    GET:      (code) => `/tickets/${code}`,
    QR:       (code) => `/tickets/${code}/qr`,
    DOWNLOAD: (code) => `/tickets/${code}/download`,
  },
  REVIEWS: {
    ADD:    (eventId) => `/events/${eventId}/reviews`,
    LIST:   (eventId) => `/events/${eventId}/reviews`,
    UPDATE: (id)      => `/reviews/${id}`,
    DELETE: (id)      => `/reviews/${id}`,
    MY:     '/reviews/my',
  },
  USERS: {
    GET:     (id) => `/users/${id}`,
    PROFILE: '/users/profile',
    AVATAR:  '/users/avatar',
  },
  WISHLIST: {
    TOGGLE: (eventId) => `/wishlist/events/${eventId}`,
    MY:     '/wishlist',
    CHECK:  (eventId) => `/wishlist/events/${eventId}/check`,
  },
  ATTENDANCE: {
    SCAN:  '/attendance/scan',
    EVENT: (id) => `/attendance/events/${id}`,
    STATS: (id) => `/attendance/events/${id}/stats`,
  },
  PAYMENTS: {
    CREATE_ORDER: (regId) => `/payments/create-order/${regId}`,
    VERIFY:       '/payments/verify',
    MY:           '/payments/my',
  },
  NOTIFICATIONS: {
    LIST:        '/notifications',
    UNREAD:      '/notifications/unread-count',
    READ:        (id) => `/notifications/${id}/read`,
    READ_ALL:    '/notifications/read-all',
    DELETE_READ: '/notifications/read',
  },
  CERTIFICATES: {
    MY:       '/certificates/my',
    DOWNLOAD: (code) => `/certificates/${code}/download`,
    VERIFY:   (code) => `/certificates/${code}/verify`,
  },
  CATEGORIES: {
    LIST: '/categories',
    GET:  (id) => `/categories/${id}`,
  },
  COUPONS: {
    VALIDATE: '/coupons/validate',
  },
  // ✅ NEW: Organizer account requests
  ORGANIZER_REQUESTS: {
    SUBMIT:        '/organizer-requests',
    LIST:          '/organizer-requests',
    PENDING_COUNT: '/organizer-requests/pending-count',
    APPROVE:       (id) => `/organizer-requests/${id}/approve`,
    REJECT:        (id) => `/organizer-requests/${id}/reject`,
  },
  ADMIN: {
    DASHBOARD:        '/admin/dashboard',
    ANALYTICS:        '/admin/analytics',
    USERS:            '/admin/users',
    USER:             (id)      => `/admin/users/${id}`,
    USER_TOGGLE:      (id)      => `/admin/users/${id}/toggle-status`,
    USERS_BY_ROLE:    (role)    => `/admin/users/role/${role}`,
    EVENTS:           '/admin/events',
    EVENT_DELETE:     (id)      => `/admin/events/${id}`,
    ATTENDANCE_STATS: (eventId) => `/admin/events/${eventId}/attendance/stats`,
    ATTENDANCE_LIST:  (eventId) => `/admin/events/${eventId}/attendance`,
    REVIEWS:          '/admin/reviews',
    REVIEW_DELETE:    (id)      => `/admin/reviews/${id}`,
    CATEGORIES:       '/admin/categories',
    CATEGORY_UPDATE:  (id)      => `/admin/categories/${id}`,
    CATEGORY_DELETE:  (id)      => `/admin/categories/${id}`,
    COUPONS:          '/admin/coupons',
    COUPON_UPDATE:    (id)      => `/admin/coupons/${id}`,
    COUPON_DELETE:    (id)      => `/admin/coupons/${id}`,
    PAYMENTS:         '/admin/payments',
    NOTIFY_BROADCAST: '/admin/notifications/broadcast',
    NOTIFY_USER:      '/admin/notifications/user',
    CERT_GENERATE:    '/admin/certificates/generate',
  },
  ORGANIZER: {
    DASHBOARD:     '/organizer/dashboard',
    EVENTS:        '/organizer/events',
    REGISTRATIONS: (eventId)         => `/organizer/events/${eventId}/registrations`,
    ATTENDANCE:    (eventId)         => `/organizer/events/${eventId}/attendance`,
    ATT_STATS:     (eventId)         => `/organizer/events/${eventId}/attendance/stats`,
    CERTIFICATE:   (eventId, userId) => `/organizer/events/${eventId}/certificates/${userId}`,
  },
};

export default EP;